#!/usr/bin/env node
/* mermaid-to-quickagram — convert a Mermaid diagram source into a
 * Quickagram diagram literal.
 *
 *   node tools/mermaid-to-quickagram/index.js input.mmd
 *   node tools/mermaid-to-quickagram/index.js input.mmd --json
 *   node tools/mermaid-to-quickagram/index.js input.mmd -o out.js
 *   cat diagram.mmd | node tools/mermaid-to-quickagram/index.js -
 *
 * Supports flowchart / sequenceDiagram / classDiagram / stateDiagram(-v2).
 */
'use strict';

const fs   = require('fs');
const path = require('path');

const { sniffKind }       = require('./sniff');
const { parseFlowchart }  = require('./parse-flowchart');
const { parseSequence }   = require('./parse-sequence');
const { parseClass }      = require('./parse-class');
const { parseState }      = require('./parse-state');
const { build, prettyJS } = require('./emit');

function parseArgs(argv) {
  const a = { input: null, out: null, json: false };
  for (let i = 0; i < argv.length; i++) {
    const x = argv[i];
    if (x === '-o' || x === '--out')  a.out  = argv[++i];
    else if (x === '--json')          a.json = true;
    else if (x === '-h' || x === '--help') { printUsage(); process.exit(0); }
    else if (!a.input)                a.input = x;
  }
  return a;
}

function printUsage() {
  console.error('Usage: mermaid-to-quickagram <input.mmd|-> [-o out.js] [--json]');
  console.error('');
  console.error('Supported diagram types:');
  console.error('  flowchart        Mermaid `flowchart` / `graph`');
  console.error('  sequence         Mermaid `sequenceDiagram`');
  console.error('  class            Mermaid `classDiagram` / `classDiagram-v2`');
  console.error('  state            Mermaid `stateDiagram` / `stateDiagram-v2`');
}

function readInput(p) {
  if (p === '-' || p == null) return fs.readFileSync(0, 'utf8');
  return fs.readFileSync(path.resolve(p), 'utf8');
}

function dispatch(kind, src) {
  switch (kind) {
    case 'flowchart': return parseFlowchart(src);
    case 'sequence':  return parseSequence(src);
    case 'class':     return parseClass(src);
    case 'state':     return parseState(src);
  }
  throw new Error('unsupported diagram type: ' + kind);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.input && process.stdin.isTTY) {
    printUsage(); process.exit(1);
  }
  const src  = readInput(args.input);
  const kind = sniffKind(src);
  if (!kind) {
    console.error('error: could not detect Mermaid diagram type from header');
    process.exit(1);
  }
  let ast;
  try { ast = dispatch(kind, src); }
  catch (e) {
    console.error('error: ' + e.message);
    process.exit(1);
  }
  const diagram = build(ast);
  const out = args.json ? JSON.stringify(diagram, null, 2) : prettyJS(diagram);
  const banner = args.json ? '' :
    '/* generated by mermaid-to-quickagram from ' +
    (args.input && args.input !== '-' ? path.basename(args.input) : 'stdin') +
    ' — kind: ' + ast.kind + ' */\n';
  const final = banner + out;
  if (args.out) fs.writeFileSync(args.out, final + '\n');
  else process.stdout.write(final + '\n');
}

if (require.main === module) main();

module.exports = { dispatch, build, prettyJS, sniffKind };
